@extends('layouts.app')
@section('content')
  <div class="container">
    DIRECTORIO PRUEBA DENUE
    <table class="table table-striped">
    <thead>
        <tr>
            <th>#id_denue</th>
            <th>clee</th>
            <th>nombre_unidad</th>
            <th>razon_social</th>
            <th>codigo_scian</th>
            <th>nombre_clase_actividad</th>
            <th>descripcion_estrato_personal_ocupado</th>
            <th>tipo_vialidad</th>
            <th>nombre_vialidad</th>
            <th>tipo_entre_vialidad_1</th>
            <th>nombre_entre_vialidad_1</th>
            <th>tipo_entre_vialidad_2</th>
            <th>nombre_entre_vialidad_2</th>
            <th>tipo_entre_vialidad_3</th>
            <th>nombre_entre_vialidad_3</th>
            <th>numero_exterior_o_kilometro</th>
            <th>letra_exterior</th>
            <th>edificio</th>
            <th>edificio_piso</th>
            <th>numero_interior</th>
            <th>letra_interior</th>
            <th>tipo_asentamiento_humano</th>
            <th>nombre_asentamiento_humano</th>
            <th>tipo_centro_comercial</th>
            <th>corredor_industrial_comercial_mercado</th>
            <th>numero_local</th>
            <th>codigo_postal</th>
            <th>clave_entidad</th>
            <th>entidad_federativa</th>
            <th>clave_municipio</th>
            <th>municipio</th>
            <th>clave_localidad</th>
            <th>localidad</th>
            <th>area_geoestadistica</th>
            <th>manzana</th>
            <th>numero_telefono</th>
            <th>correo_electronico</th>
            <th>sitio_internet</th>
            <th>tipo_establecimiento</th>
            <th>latitud</th>
            <th>longitud</th>
            <th>fecha_incorporacion_denue</th>
        </tr>
    </thead>
    <tbody>
        @foreach($directories as $data)
        <tr>
            <td>{{$data->id_denue}}</td>
            <td>{{$data->clee}}</td>
            <td>{{$data->nombre_unidad}}</td>
            <td>{{$data->razon_social}}</td>
            <td>{{$data->codigo_scian}}</td>
            <td>{{$data->nombre_clase_actividad}}</td>
            <td>{{$data->descripcion_estrato_personal_ocupado}}</td>
            <td>{{$data->tipo_vialidad}}</td>
            <td>{{$data->nombre_vialidad}}</td>
            <td>{{$data->tipo_entre_vialidad_1}}</td>
            <td>{{$data->nombre_entre_vialidad_1}}</td>
            <td>{{$data->tipo_entre_vialidad_2}}</td>
            <td>{{$data->nombre_entre_vialidad_2}}</td>
            <td>{{$data->tipo_entre_vialidad_3}}</td>
            <td>{{$data->nombre_entre_vialidad_3}}</td>
            <td>{{$data->numero_exterior_o_kilometro}}</td>
            <td>{{$data->letra_exterior}}</td>
            <td>{{$data->edificio}}</td>
            <td>{{$data->edificio_piso}}</td>
            <td>{{$data->numero_interior}}</td>
            <td>{{$data->letra_interior}}</td>
            <td>{{$data->tipo_asentamiento_humano}}</td>
            <td>{{$data->nombre_asentamiento_humano}}</td>
            <td>{{$data->tipo_centro_comercial}}</td>
            <td>{{$data->corredor_industrial_comercial_mercado}}</td>
            <td>{{$data->numero_local}}</td>
            <td>{{$data->codigo_postal}}</td>
            <td>{{$data->clave_entidad}}</td>
            <td>{{$data->entidad_federativa}}</td>
            <td>{{$data->clave_municipio}}</td>
            <td>{{$data->municipio}}</td>
            <td>{{$data->clave_localidad}}</td>
            <td>{{$data->localidad}}</td>
            <td>{{$data->area_geoestadistica}}</td>
            <td>{{$data->manzana}}</td>
            <td>{{$data->numero_telefono}}</td>
            <td>{{$data->correo_electronico}}</td>
            <td>{{$data->sitio_internet}}</td>
            <td>{{$data->tipo_establecimiento}}</td>
            <td>{{$data->latitud}}</td>
            <td>{{$data->longitud}}</td>
            <td>{{$data->fecha_incorporacion_denue}}</td>
        </tr>
        @endforeach
    </tbody>
    </table>
  </div>
@endsection